# L'obiettivo dell'esercizio è prendere l'immagine Docker dell'app Flask e
# farla girare su Kubernetes usando Helm

# per importare il tag dinamico si utilizza il comando "helm install appy . --set image.tag=latest"

replicaCount: 1

image:
  repository: j3ynn/flask-hello-world
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}