//variabile
def IMAGE_TAG = ""

pipeline {
    agent any //esegue la pipeline su qualsiasi agent disponibile, nel mio caso ContainerAgent (step1)

    //contenitore (es. tasks)
    stages {

        //debug per capire quali variabili sono disponibili
        stage('Debug Git Vars') {
            steps {
                sh 'env | grep -i git'
                sh 'env | grep -i branch'
                sh 'env | grep -i tag'
            }
        }

        stage('Set Image Tag') {
            steps {
                script {
                    if (env.GIT_BRANCH == "origin/master") {
                        IMAGE_TAG = "latest"
                    }
                    else if (env.GIT_BRANCH == "origin/develop") {
                        IMAGE_TAG = "develop-" + env.GIT_COMMIT.take(7) //prende solo i primi 7 caratteri della stringa SHA
                    }
                    else {
                        IMAGE_TAG = env.TAG_NAME
                    }
                }
            }
        }
        // SHA = famiglia di algoritmi crittografici utilizzati per trasformare una quantità di dati in una stringa di caratteri dall'aspetto casuale.

        //prima di questo ho creato le credenziali globali su jenkins,
        //facendo così non sono visibili le password ma salvate in una variabile globale
        stage('Login DockerHub') {
            steps {
                //recupera le credenziali di accesso su jenkins
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials', //prende le informazioni della credenziale globale su jenkins
                    usernameVariable: 'DOCKER_USER', //mette l'user nella variabile globale
                    passwordVariable: 'DOCKER_PASS' //mette la password nella variabile globale
                )]) {
                    sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin' //comando per il login dockerhub
                }
            }
        }

        //nome stage
        stage('Build') {
            //step da eseguire
            steps {
                echo "inizio Build [creazione immagine]"
                //SH esegue il comando da terminale. 
                sh 'docker build -t flask-hello-world Step2/' //crea immagine
            }
        }
    
        stage('Tag') {
            steps {
                echo "inizio tag imag"
                sh "docker tag flask-hello-world j3ynn/flask-hello-world:${IMAGE_TAG}" //tagga immagine
            }
        }

        stage('Push') {
            steps {
                echo "inizio push"
                sh "docker push j3ynn/flask-hello-world:${IMAGE_TAG}" //pusha su dockerhub l'immagine
            }
        }
    }
    
    //qualunque cosa succeda, alla fine della sessione Docker viene chiuso
    post {
        always {
            sh 'docker logout'
        }
    }
}
